run:
  project: Michaud_v1_AllCases_fullpipeline
  select:
    cases:    ["BetasMicCas"]
    controls: ["BetasMicCon"]

paths:
  annotations: data/annotations/Anno320K.csv
  raw_datasets_root: data/rawdatasets
  datasets_root: data/datasets
  norm_controls_root: data/msemetrics/controlsdatasets
  admodel: models/heavymodelv1
  msemetrics: data/msemetrics
  recscores: data/recscores
  mlmodels: data/reports/mlmodels
  reports: data/reports

recscores:
  group_size: 1
  missing_value: -1
  
mlmodels:
  beta_values: true
  out_dir: data/reports/mlmodels
  n_splits: 5
  random_state: 42
  apply_feature_filter: false
  feature_filter_threshold: 0.01
  max_features: 500
  n_bootstrap: 1000
  n_jobs: 8
  
plots:
  mlmodels_modes: ["rec", "beta"]   

functional:
  term: "Pancreatic cancer"   
  top_n_cpg: 100              

  