paths:
  annotations: data/annotations/Anno320K.csv
  raw:
    cases_files:
      - data/datasets/cases/FraCas_float16.npy
    controls_files:
      - data/datasets/controls/FraCon_float16.npy
  admodel: models/heavymodelv1
  msemetrics: data/msemetrics
  processed: data/processed
  reports: data/reports

preprocess:
  impute: true
  normalize: zscore

train:
  model: xgboost        
  n_jobs: 4
  random_state: 42

evaluate:
  metrics: [auc, accuracy, f1]

plots:
  format: png
  dpi: 150
